sudo: false
language: ruby
rvm:
  - 2.2.3
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
   - bundle exec rspec
   - bundle exec rubocop --config .rubocop.yml
