language: ruby
rvm:
- 2.5.0
before_install: gem update --remote bundler
install:
- bundle install --retry=3
script:
- bundle exec rspec
- bundle exec rubocop --config .rubocop.yml
- bundle exec codeclimate-test-reporter
